import { Product } from './types';

// Full dataset extracted from the provided OCR text.
export const products: Product[] = [
  // Page 1
  {
    id: "01/CL/TH/1",
    code: "01/CL/TH/1",
    englishName: "Anchovy",
    malayalamName: "നെത്തോലി/കൊഴുവ",
    preparation: "Cleaned",
    packaging: "Thermal Box",
    sizeSpec: "40-50 pcs",
    priceDiamond: 8.51,
    pricePlatinum: 8.88,
    priceGold: 9.25,
    priceSilver: 9.62
  },
  {
    id: "01/CL/VA/1",
    code: "01/CL/VA/1",
    englishName: "Anchovy",
    malayalamName: "നെത്തോലി/കൊഴുവ",
    preparation: "Cleaned",
    packaging: "Vacuum Pack",
    sizeSpec: "40-50 pcs",
    priceDiamond: 9.09,
    pricePlatinum: 9.48,
    priceGold: 9.88,
    priceSilver: 10.27
  },
  {
    id: "02/WH/TH/2",
    code: "02/WH/TH/2",
    englishName: "Barramundi",
    malayalamName: "കാളാഞ്ചി",
    preparation: "Whole",
    packaging: "Thermal Box",
    sizeSpec: "1-2 kg",
    priceDiamond: 9.49,
    pricePlatinum: 9.90,
    priceGold: 10.31,
    priceSilver: 10.73
  },
  {
    id: "02/WH/TH/1",
    code: "02/WH/TH/1",
    englishName: "Barramundi",
    malayalamName: "കാളാഞ്ചി",
    preparation: "Whole",
    packaging: "Thermal Box",
    sizeSpec: "2-4kg",
    priceDiamond: 9.26,
    pricePlatinum: 9.66,
    priceGold: 10.06,
    priceSilver: 10.47
  },
  {
    id: "02/CL/TH/1",
    code: "02/CL/TH/1",
    englishName: "Barramundi",
    malayalamName: "കാളാഞ്ചി",
    preparation: "Cleaned",
    packaging: "Thermal Box",
    sizeSpec: "2-4 kg",
    priceDiamond: 10.41,
    pricePlatinum: 10.86,
    priceGold: 11.31,
    priceSilver: 11.77
  },
  {
    id: "02/CL/VA/1",
    code: "02/CL/VA/1",
    englishName: "Barramundi",
    malayalamName: "കാളാഞ്ചി",
    preparation: "Cleaned",
    packaging: "Vacuum Pack",
    sizeSpec: "2-4 kg",
    priceDiamond: 11.33,
    pricePlatinum: 11.82,
    priceGold: 12.31,
    priceSilver: 12.81
  },
  {
    id: "03/WH/TH/1",
    code: "03/WH/TH/1",
    englishName: "Barracuda",
    malayalamName: "ശീലാവ്",
    preparation: "Whole",
    packaging: "Thermal Box",
    sizeSpec: "5 kg",
    priceDiamond: 8.45,
    pricePlatinum: 8.82,
    priceGold: 9.19,
    priceSilver: 9.56
  },
  {
    id: "03/WH/TH/2",
    code: "03/WH/TH/2",
    englishName: "Barracuda",
    malayalamName: "ശീലാവ്",
    preparation: "Whole",
    packaging: "Thermal Box",
    sizeSpec: "1 -2 kg",
    priceDiamond: 7.71,
    pricePlatinum: 8.04,
    priceGold: 8.38,
    priceSilver: 8.71
  },
  {
    id: "03/CL/TH/3",
    code: "03/CL/TH/3",
    englishName: "Barracuda",
    malayalamName: "ശീലാവ്",
    preparation: "Cleaned",
    packaging: "Thermal Box",
    sizeSpec: "2-3 kg",
    priceDiamond: 9.78,
    pricePlatinum: 10.20,
    priceGold: 10.63,
    priceSilver: 11.05
  },
  {
    id: "03/CL/VA/3",
    code: "03/CL/VA/3",
    englishName: "Barracuda",
    malayalamName: "ശീലാവ്",
    preparation: "Cleaned",
    packaging: "Vacuum Pack",
    sizeSpec: "2-3 kg",
    priceDiamond: 11.27,
    pricePlatinum: 11.76,
    priceGold: 12.25,
    priceSilver: 12.74
  },
  {
    id: "03/CH/VA/3",
    code: "03/CH/VA/3",
    englishName: "Barracuda",
    malayalamName: "ശീലാവ്",
    preparation: "Chunk",
    packaging: "Vacuum Pack",
    sizeSpec: "2-3 kg",
    priceDiamond: 13.36,
    pricePlatinum: 13.94,
    priceGold: 14.53,
    priceSilver: 15.11
  },
  {
    id: "04/WH/TH/2",
    code: "04/WH/TH/2",
    englishName: "Black kingfish",
    malayalamName: "മോത/കരയിലാവു",
    preparation: "Whole",
    packaging: "Thermal Box",
    sizeSpec: "3-8 kg",
    priceDiamond: 9.23,
    pricePlatinum: 9.64,
    priceGold: 10.04,
    priceSilver: 10.44
  },
  {
    id: "04/CL/TH/3",
    code: "04/CL/TH/3",
    englishName: "Black kingfish",
    malayalamName: "മോത/കരയിലാവു",
    preparation: "Cleaned",
    packaging: "Thermal Box",
    sizeSpec: "1-2 kg",
    priceDiamond: 11.44,
    pricePlatinum: 11.94,
    priceGold: 12.44,
    priceSilver: 12.94
  },
  {
    id: "04/CL/VA/3",
    code: "04/CL/VA/3",
    englishName: "Black kingfish",
    malayalamName: "മോത/കരയിലാവു",
    preparation: "Cleaned",
    packaging: "Vacuum Pack",
    sizeSpec: "1-2 kg",
    priceDiamond: 12.59,
    pricePlatinum: 13.14,
    priceGold: 13.69,
    priceSilver: 14.24
  },
  {
    id: "05/WH/TH/2",
    code: "05/WH/TH/2",
    englishName: "Black pomfret",
    malayalamName: "കറുത്ത ആവോലി",
    preparation: "Whole",
    packaging: "Thermal Box",
    sizeSpec: "1 - 2kg",
    priceDiamond: 12.19,
    pricePlatinum: 12.72,
    priceGold: 13.25,
    priceSilver: 13.78
  },
  {
    id: "05/WH/TH/1",
    code: "05/WH/TH/1",
    englishName: "Black pomfret",
    malayalamName: "കറുത്ത ആവോലി",
    preparation: "Whole",
    packaging: "Thermal Box",
    sizeSpec: "300g - 1kg/pc",
    priceDiamond: 11.02,
    pricePlatinum: 11.50,
    priceGold: 11.98,
    priceSilver: 12.45
  },
  {
    id: "05/CL/TH/1",
    code: "05/CL/TH/1",
    englishName: "Black pomfret",
    malayalamName: "കറുത്ത ആവോലി",
    preparation: "Cleaned",
    packaging: "Thermal Box",
    sizeSpec: "300g - 1kg/pc",
    priceDiamond: 12.22,
    pricePlatinum: 12.76,
    priceGold: 13.29,
    priceSilver: 13.82
  },
  {
    id: "05/CL/VA/1",
    code: "05/CL/VA/1",
    englishName: "Black pomfret",
    malayalamName: "കറുത്ത ആവോലി",
    preparation: "Cleaned",
    packaging: "Vacuum Pack",
    sizeSpec: "300g - 1kg/pc",
    priceDiamond: 13.95,
    pricePlatinum: 14.56,
    priceGold: 15.16,
    priceSilver: 15.77
  },
  {
    id: "06/WH/TH/1",
    code: "06/WH/TH/1",
    englishName: "Cobia",
    malayalamName: "മോത",
    preparation: "Whole",
    packaging: "Thermal Box",
    sizeSpec: "1-2 kg/pc",
    priceDiamond: 9.49,
    pricePlatinum: 9.90,
    priceGold: 10.31,
    priceSilver: 10.73
  },
  {
    id: "06/CL/TH/1",
    code: "06/CL/TH/1",
    englishName: "Cobia",
    malayalamName: "മോത",
    preparation: "Cleaned",
    packaging: "Thermal Box",
    sizeSpec: "1-2 kg/pc",
    priceDiamond: 10.47,
    pricePlatinum: 10.92,
    priceGold: 11.38,
    priceSilver: 11.83
  },
  {
    id: "06/CL/VA/1",
    code: "06/CL/VA/1",
    englishName: "Cobia",
    malayalamName: "മോത",
    preparation: "Cleaned",
    packaging: "Vacuum Pack",
    sizeSpec: "1-2 kg/pc",
    priceDiamond: 11.50,
    pricePlatinum: 12.00,
    priceGold: 12.50,
    priceSilver: 13.00
  },
  {
    id: "07/WH/TH/1",
    code: "07/WH/TH/1",
    englishName: "Crab",
    malayalamName: "ഞണ്ട്",
    preparation: "Whole",
    packaging: "Thermal Box",
    sizeSpec: "300 gm & up",
    priceDiamond: 8.43,
    pricePlatinum: 8.80,
    priceGold: 9.16,
    priceSilver: 9.53
  },
  {
    id: "07/WH/TH/2",
    code: "07/WH/TH/2",
    englishName: "Crab",
    malayalamName: "ഞണ്ട്",
    preparation: "Whole",
    packaging: "Thermal Box",
    sizeSpec: "200 - 250 gm",
    priceDiamond: 10.93,
    pricePlatinum: 11.40,
    priceGold: 11.88,
    priceSilver: 12.35
  },
  {
    id: "07/CL/TH/2",
    code: "07/CL/TH/2",
    englishName: "Crab",
    malayalamName: "ഞണ്ട്",
    preparation: "Cleaned",
    packaging: "Thermal Box",
    sizeSpec: "200 - 250 gm",
    priceDiamond: 11.37,
    pricePlatinum: 11.87,
    priceGold: 12.36,
    priceSilver: 12.86
  },
  {
    id: "08/WH/TH/1",
    code: "08/WH/TH/1",
    englishName: "Emperor fish",
    malayalamName: "ഏരി",
    preparation: "Whole",
    packaging: "Thermal Box",
    sizeSpec: "400-500 gm",
    priceDiamond: 9.03,
    pricePlatinum: 9.42,
    priceGold: 9.81,
    priceSilver: 10.21
  },
  {
    id: "08/WH/TH/3",
    code: "08/WH/TH/3",
    englishName: "Emperor fish",
    malayalamName: "ഏരി",
    preparation: "Whole",
    packaging: "Thermal Box",
    sizeSpec: "1 kg",
    priceDiamond: 8.42,
    pricePlatinum: 8.78,
    priceGold: 9.15,
    priceSilver: 9.52
  },
  {
    id: "08/CL/TH/2",
    code: "08/CL/TH/2",
    englishName: "Emperor fish",
    malayalamName: "ഏരി",
    preparation: "Cleaned",
    packaging: "Thermal Box",
    sizeSpec: "250-350 gm",
    priceDiamond: 9.83,
    pricePlatinum: 10.26,
    priceGold: 10.69,
    priceSilver: 11.12
  },
  {
    id: "08/CL/VA/2",
    code: "08/CL/VA/2",
    englishName: "Emperor fish",
    malayalamName: "ഏരി",
    preparation: "Cleaned",
    packaging: "Vacuum Pack",
    sizeSpec: "250-350 gm",
    priceDiamond: 10.75,
    pricePlatinum: 11.22,
    priceGold: 11.69,
    priceSilver: 12.16
  },
  {
    id: "09/WH/TH/1",
    code: "09/WH/TH/1",
    englishName: "Grey mullet",
    malayalamName: "തിരുത/ കണമ്പ്",
    preparation: "Whole",
    packaging: "Thermal Box",
    sizeSpec: "4-6 pcs",
    priceDiamond: 7.48,
    pricePlatinum: 7.80,
    priceGold: 8.13,
    priceSilver: 8.45
  },
  {
    id: "09/CL/TH/2",
    code: "09/CL/TH/2",
    englishName: "Grey mullet",
    malayalamName: "തിരുത/ കണമ്പ്",
    preparation: "Cleaned",
    packaging: "Thermal Box",
    sizeSpec: "6-8 pcs",
    priceDiamond: 8.40,
    pricePlatinum: 8.76,
    priceGold: 9.13,
    priceSilver: 9.49
  },
  {
    id: "09/CL/VA/2",
    code: "09/CL/VA/2",
    englishName: "Grey mullet",
    malayalamName: "തിരുത/ കണമ്പ്",
    preparation: "Cleaned",
    packaging: "Vacuum Pack",
    sizeSpec: "6-8 pcs",
    priceDiamond: 9.55,
    pricePlatinum: 9.96,
    priceGold: 10.38,
    priceSilver: 10.79
  },
  {
    id: "10/WH/TH/1",
    code: "10/WH/TH/1",
    englishName: "King Fish/ Seer fish (1-3kg)",
    malayalamName: "നെയമീൻ",
    preparation: "Whole",
    packaging: "Thermal Box",
    sizeSpec: "3 kg/pc",
    priceDiamond: 10.42,
    pricePlatinum: 10.87,
    priceGold: 11.33,
    priceSilver: 11.78
  },
  {
    id: "10/WH/TH/2",
    code: "10/WH/TH/2",
    englishName: "King Fish / Seer fish (5 - 8 kg)",
    malayalamName: "നെയമീൻ",
    preparation: "Whole",
    packaging: "Thermal Box",
    sizeSpec: "5 kg/pc",
    priceDiamond: 11.79,
    pricePlatinum: 12.30,
    priceGold: 12.81,
    priceSilver: 13.33
  },
  {
    id: "10/ST/VA/2",
    code: "10/ST/VA/2",
    englishName: "King Fish / Seer fish (5 - 8 kg)",
    malayalamName: "നെയമീൻ",
    preparation: "Steak",
    packaging: "Vacuum Pack",
    sizeSpec: "5 kg/pc",
    priceDiamond: 12.94,
    pricePlatinum: 13.50,
    priceGold: 14.06,
    priceSilver: 14.63
  },
  {
    id: "11/CL/TH/1",
    code: "11/CL/TH/1",
    englishName: "Lizard fish",
    malayalamName: "ചൂരാറ",
    preparation: "Cleaned",
    packaging: "Thermal Box",
    sizeSpec: "4-6 pcs",
    priceDiamond: 8.30,
    pricePlatinum: 8.66,
    priceGold: 9.03,
    priceSilver: 9.39
  },
  {
    id: "11/CL/VA/1",
    code: "11/CL/VA/1",
    englishName: "Lizard fish",
    malayalamName: "ചൂരാറ",
    preparation: "Cleaned",
    packaging: "Vacuum Pack",
    sizeSpec: "4-6 pcs",
    priceDiamond: 10.03,
    pricePlatinum: 10.46,
    priceGold: 10.90,
    priceSilver: 11.34
  },
  {
    id: "12/WH/TH/1",
    code: "12/WH/TH/1",
    englishName: "Mackerel",
    malayalamName: "അയല",
    preparation: "Whole",
    packaging: "Thermal Box",
    sizeSpec: "8-10 pcs",
    priceDiamond: 7.62,
    pricePlatinum: 7.96,
    priceGold: 8.29,
    priceSilver: 8.62
  },
  {
    id: "12/CL/TH/2",
    code: "12/CL/TH/2",
    englishName: "Mackerel",
    malayalamName: "അയല",
    preparation: "Cleaned",
    packaging: "Thermal Box",
    sizeSpec: "8-10 pcs",
    priceDiamond: 8.64,
    pricePlatinum: 9.01,
    priceGold: 9.39,
    priceSilver: 9.76
  },
  {
    id: "12/CL/VA/2",
    code: "12/CL/VA/2",
    englishName: "Mackerel",
    malayalamName: "അയല",
    preparation: "Cleaned",
    packaging: "Vacuum Pack",
    sizeSpec: "8-10 pcs",
    priceDiamond: 8.64,
    pricePlatinum: 9.01,
    priceGold: 9.39,
    priceSilver: 9.76
  },
  {
    id: "13/WH/TH/1",
    code: "13/WH/TH/1",
    englishName: "Mahi Mahi",
    malayalamName: "പുള്ളി മോത",
    preparation: "Whole",
    packaging: "Thermal Box",
    sizeSpec: "1-2 kg/pc",
    priceDiamond: 8.43,
    pricePlatinum: 8.80,
    priceGold: 9.16,
    priceSilver: 9.53
  },
  {
    id: "13/CL/TH/1",
    code: "13/CL/TH/1",
    englishName: "Mahi Mahi",
    malayalamName: "പുള്ളി മോത",
    preparation: "Cleaned",
    packaging: "Thermal Box",
    sizeSpec: "1-2 kg/pc",
    priceDiamond: 9.95,
    pricePlatinum: 10.38,
    priceGold: 10.81,
    priceSilver: 11.25
  },
  {
    id: "13/CL/VA/1",
    code: "13/CL/VA/1",
    englishName: "Mahi Mahi",
    malayalamName: "പുള്ളി മോത",
    preparation: "Cleaned",
    packaging: "Vacuum Pack",
    sizeSpec: "1-2 kg/pc",
    priceDiamond: 9.95,
    pricePlatinum: 10.38,
    priceGold: 10.81,
    priceSilver: 11.25
  },
  {
    id: "14/WH/TH/1",
    code: "14/WH/TH/1",
    englishName: "Pearl Spot",
    malayalamName: "കരിമീൻ/ കോറൽ",
    preparation: "Whole",
    packaging: "Thermal Box",
    sizeSpec: "4-5 pcs",
    priceDiamond: 9.78,
    pricePlatinum: 10.20,
    priceGold: 10.63,
    priceSilver: 11.05
  },
  {
    id: "14/CL/TH/1",
    code: "14/CL/TH/1",
    englishName: "Pearl Spot",
    malayalamName: "കരിമീൻ/ കോറൽ",
    preparation: "Cleaned",
    packaging: "Thermal Box",
    sizeSpec: "4-5 pcs",
    priceDiamond: 10.93,
    pricePlatinum: 11.40,
    priceGold: 11.88,
    priceSilver: 12.35
  },
  {
    id: "14/MC/VA/1",
    code: "14/MC/VA/1",
    englishName: "Pearl Spot",
    malayalamName: "കരിമീൻ/ കോറൽ",
    preparation: "Moon Cut",
    packaging: "Vacuum Pack",
    sizeSpec: "4-5 pcs",
    priceDiamond: 12.08,
    pricePlatinum: 12.60,
    priceGold: 13.13,
    priceSilver: 13.65
  },
  {
    id: "15/WH/TH/1",
    code: "15/WH/TH/1",
    englishName: "Red Snapper",
    malayalamName: "ചെമ്പല്ലി",
    preparation: "Whole",
    packaging: "Thermal Box",
    sizeSpec: "0.5 - 2 kg/pc",
    priceDiamond: 8.43,
    pricePlatinum: 8.80,
    priceGold: 9.16,
    priceSilver: 9.53
  },
  {
    id: "15/CL/TH/1",
    code: "15/CL/TH/1",
    englishName: "Red Snapper",
    malayalamName: "ചെമ്പല്ലി",
    preparation: "Cleaned",
    packaging: "Thermal Box",
    sizeSpec: "0.5 - 2 kg/pc",
    priceDiamond: 9.32,
    pricePlatinum: 9.72,
    priceGold: 10.13,
    priceSilver: 10.53
  },
  {
    id: "15/CL/VA/1",
    code: "15/CL/VA/1",
    englishName: "Red Snapper",
    malayalamName: "ചെമ്പല്ലി",
    preparation: "Cleaned",
    packaging: "Vacuum Pack",
    sizeSpec: "0.5 - 2 kg/pc",
    priceDiamond: 11.21,
    pricePlatinum: 11.70,
    priceGold: 12.19,
    priceSilver: 12.68
  },
  {
    id: "16/WH/TH/1",
    code: "16/WH/TH/1",
    englishName: "Ribbon fish",
    malayalamName: "വാള",
    preparation: "Whole",
    packaging: "Thermal Box",
    sizeSpec: "500-700 gm",
    priceDiamond: 7.92,
    pricePlatinum: 8.27,
    priceGold: 8.61,
    priceSilver: 8.96
  },
  {
    id: "16/CC/VA/1",
    code: "16/CC/VA/1",
    englishName: "Ribbon fish",
    malayalamName: "വാള",
    preparation: "Curry cut",
    packaging: "Vacuum Pack",
    sizeSpec: "40-50 gm",
    priceDiamond: 9.45,
    pricePlatinum: 9.86,
    priceGold: 10.28,
    priceSilver: 10.69
  },
  {
    id: "17/WH/TH/1",
    code: "17/WH/TH/1",
    englishName: "Sail Fish",
    malayalamName: "ഓലകുടിയൻ",
    preparation: "Whole",
    packaging: "Thermal Box",
    sizeSpec: "5-10 kg/pc",
    priceDiamond: 8.97,
    pricePlatinum: 9.36,
    priceGold: 9.75,
    priceSilver: 10.14
  },
  {
    id: "17/CH/VA/1",
    code: "17/CH/VA/1",
    englishName: "Sail Fish",
    malayalamName: "ഓലകുടിയൻ",
    preparation: "Chunk",
    packaging: "Vacuum Pack",
    sizeSpec: "5-10 kg/pc",
    priceDiamond: 11.50,
    pricePlatinum: 12.00,
    priceGold: 12.50,
    priceSilver: 13.00
  },
  {
    id: "17/CL/VA/2",
    code: "17/CL/VA/2",
    englishName: "Sail Fish",
    malayalamName: "ഓലകുടിയൻ",
    preparation: "Cleaned",
    packaging: "Vacuum Pack",
    sizeSpec: "2 - 3 kg/pc",
    priceDiamond: 10.12,
    pricePlatinum: 10.56,
    priceGold: 11.00,
    priceSilver: 11.44
  },
  {
    id: "18/WH/TH/1",
    code: "18/WH/TH/1",
    englishName: "Sardine",
    malayalamName: "ചാള/മത്തി",
    preparation: "Whole",
    packaging: "Thermal Box",
    sizeSpec: "10-15 pcs",
    priceDiamond: 6.90,
    pricePlatinum: 7.20,
    priceGold: 7.50,
    priceSilver: 7.80
  },
  {
    id: "18/CL/TH/1",
    code: "18/CL/TH/1",
    englishName: "Sardine",
    malayalamName: "ചാള/മത്തി",
    preparation: "Cleaned",
    packaging: "Thermal Box",
    sizeSpec: "10-15 pcs",
    priceDiamond: 8.05,
    pricePlatinum: 8.40,
    priceGold: 8.75,
    priceSilver: 9.10
  },
  {
    id: "18/CL/VA/1",
    code: "18/CL/VA/1",
    englishName: "Sardine",
    malayalamName: "ചാള/മത്തി",
    preparation: "Cleaned",
    packaging: "Vacuum Pack",
    sizeSpec: "10-15 pcs",
    priceDiamond: 9.20,
    pricePlatinum: 9.60,
    priceGold: 10.00,
    priceSilver: 10.40
  },
  {
    id: "19/WH/TH/1",
    code: "19/WH/TH/1",
    englishName: "Squid",
    malayalamName: "കൂന്തൽ / കണവ",
    preparation: "Whole",
    packaging: "Thermal Box",
    sizeSpec: "3-6 pcs",
    priceDiamond: 10.24,
    pricePlatinum: 10.68,
    priceGold: 11.13,
    priceSilver: 11.57
  },
  {
    id: "19/CL/TH/2",
    code: "19/CL/TH/2",
    englishName: "Squid",
    malayalamName: "കൂന്തൽ / കണവ",
    preparation: "Cleaned",
    packaging: "Thermal Box",
    sizeSpec: "6-10 pcs",
    priceDiamond: 10.70,
    pricePlatinum: 11.16,
    priceGold: 11.63,
    priceSilver: 12.09
  },
  {
    id: "19/CL/VA/2",
    code: "19/CL/VA/2",
    englishName: "Squid",
    malayalamName: "കൂന്തൽ / കണവ",
    preparation: "Cleaned",
    packaging: "Vacuum Pack",
    sizeSpec: "6-10 pcs",
    priceDiamond: 11.85,
    pricePlatinum: 12.36,
    priceGold: 12.88,
    priceSilver: 13.39
  },
  {
    id: "20/WH/TH/1",
    code: "20/WH/TH/1",
    englishName: "Japanese Threadfin Bream",
    malayalamName: "കിളിമീൻ",
    preparation: "Whole",
    packaging: "Thermal Box",
    sizeSpec: "5 - 7 pcs",
    priceDiamond: 7.71,
    pricePlatinum: 8.04,
    priceGold: 8.38,
    priceSilver: 8.71
  },
  {
    id: "20/WH/TH/2",
    code: "20/WH/TH/2",
    englishName: "Japanese Threadfin Bream",
    malayalamName: "കിളിമീൻ",
    preparation: "Whole",
    packaging: "Thermal Box",
    sizeSpec: "8-10 pcs",
    priceDiamond: 7.62,
    pricePlatinum: 7.96,
    priceGold: 8.29,
    priceSilver: 8.62
  },
  {
    id: "20/CL/TH/3",
    code: "20/CL/TH/3",
    englishName: "Japanese Threadfin Bream",
    malayalamName: "കിളിമീൻ",
    preparation: "Cleaned",
    packaging: "Thermal Box",
    sizeSpec: "4-5 pcs",
    priceDiamond: 8.64,
    pricePlatinum: 9.01,
    priceGold: 9.39,
    priceSilver: 9.76
  },
  {
    id: "20/CL/VA/3",
    code: "20/CL/VA/3",
    englishName: "Japanese Threadfin Bream",
    malayalamName: "കിളിമീൻ",
    preparation: "Cleaned",
    packaging: "Vacuum Pack",
    sizeSpec: "4-5 pcs",
    priceDiamond: 8.74,
    pricePlatinum: 9.12,
    priceGold: 9.50,
    priceSilver: 9.88
  },
  {
    id: "21/WH/TH/1",
    code: "21/WH/TH/1",
    englishName: "Tilapia",
    malayalamName: "തിലാപിയ",
    preparation: "Whole",
    packaging: "Thermal Box",
    sizeSpec: "3-4 pcs",
    priceDiamond: 7.43,
    pricePlatinum: 7.75,
    priceGold: 8.08,
    priceSilver: 8.40
  },
  {
    id: "21/CL/TH/1",
    code: "21/CL/TH/1",
    englishName: "Tilapia",
    malayalamName: "തിലാപിയ",
    preparation: "Cleaned",
    packaging: "Thermal Box",
    sizeSpec: "3-4 pcs",
    priceDiamond: 8.37,
    pricePlatinum: 8.74,
    priceGold: 9.10,
    priceSilver: 9.46
  },
  {
    id: "21/CL/VA/1",
    code: "21/CL/VA/1",
    englishName: "Tilapia",
    malayalamName: "തിലാപിയ",
    preparation: "Cleaned",
    packaging: "Vacuum Pack",
    sizeSpec: "3-4 pcs",
    priceDiamond: 10.10,
    pricePlatinum: 10.54,
    priceGold: 10.98,
    priceSilver: 11.41
  },
  {
    id: "22/WH/TH/1",
    code: "22/WH/TH/1",
    englishName: "Tomato grouper",
    malayalamName: "തക്കാളി കലവ",
    preparation: "Whole",
    packaging: "Thermal Box",
    sizeSpec: "300-500 gm",
    priceDiamond: 11.27,
    pricePlatinum: 11.76,
    priceGold: 12.25,
    priceSilver: 12.74
  },
  {
    id: "22/CL/TH/2",
    code: "22/CL/TH/2",
    englishName: "Tomato grouper",
    malayalamName: "തക്കാളി കലവ",
    preparation: "Cleaned",
    packaging: "Thermal Box",
    sizeSpec: "200-300 gm",
    priceDiamond: 12.65,
    pricePlatinum: 13.20,
    priceGold: 13.75,
    priceSilver: 14.30
  },
  {
    id: "22/CL/VA/2",
    code: "22/CL/VA/2",
    englishName: "Tomato grouper",
    malayalamName: "തക്കാളി കലവ",
    preparation: "Cleaned",
    packaging: "Vacuum Pack",
    sizeSpec: "200-300 gm",
    priceDiamond: 13.80,
    pricePlatinum: 14.40,
    priceGold: 15.00,
    priceSilver: 15.60
  },
  {
    id: "23/WH/TH/1",
    code: "23/WH/TH/1",
    englishName: "Trevally",
    malayalamName: "വറ്റ /ചൂരാറ",
    preparation: "Whole",
    packaging: "Thermal Box",
    sizeSpec: "5+ kg/pc",
    priceDiamond: 9.18,
    pricePlatinum: 9.58,
    priceGold: 9.98,
    priceSilver: 10.37
  },
  // Page 2
  {
    id: "23/CC/VA/1",
    code: "23/CC/VA/1",
    englishName: "Trevally",
    malayalamName: "വറ്റ /ചൂരാറ",
    preparation: "Curry cut",
    packaging: "Vacuum Pack",
    sizeSpec: "5+ kg/pc",
    priceDiamond: 13.59,
    pricePlatinum: 14.18,
    priceGold: 14.78,
    priceSilver: 15.37
  },
  {
    id: "23/WH/TH/2",
    code: "23/WH/TH/2",
    englishName: "Trevally",
    malayalamName: "വറ്റ /ചൂരാറ",
    preparation: "Whole",
    packaging: "Thermal Box",
    sizeSpec: "1-1.15 kg/pc",
    priceDiamond: 8.13,
    pricePlatinum: 8.48,
    priceGold: 8.84,
    priceSilver: 9.19
  },
  {
    id: "23/CC/VA/2",
    code: "23/CC/VA/2",
    englishName: "Trevally",
    malayalamName: "വറ്റ /ചൂരാറ",
    preparation: "Curry cut",
    packaging: "Vacuum Pack",
    sizeSpec: "1-1.15 kg/pc",
    priceDiamond: 9.30,
    pricePlatinum: 9.71,
    priceGold: 10.11,
    priceSilver: 10.52
  },
  {
    id: "24/WH/TH/1",
    code: "24/WH/TH/1",
    englishName: "Tuna",
    malayalamName: "ചൂര",
    preparation: "Whole",
    packaging: "Thermal Box",
    sizeSpec: "1-2 kg/pc",
    priceDiamond: 7.43,
    pricePlatinum: 7.75,
    priceGold: 8.08,
    priceSilver: 8.40
  },
  {
    id: "24/CL/TH/1",
    code: "24/CL/TH/1",
    englishName: "Tuna",
    malayalamName: "ചൂര",
    preparation: "Cleaned",
    packaging: "Thermal Box",
    sizeSpec: "1-2 kg/pc",
    priceDiamond: 7.88,
    pricePlatinum: 8.22,
    priceGold: 8.56,
    priceSilver: 8.91
  },
  {
    id: "24/CL/VA/1",
    code: "24/CL/VA/1",
    englishName: "Tuna",
    malayalamName: "ചൂര",
    preparation: "Cleaned",
    packaging: "Vacuum Pack",
    sizeSpec: "1-2 kg/pc",
    priceDiamond: 9.60,
    pricePlatinum: 10.02,
    priceGold: 10.44,
    priceSilver: 10.86
  },
  {
    id: "25/CL/TH/1",
    code: "25/CL/TH/1",
    englishName: "Yellow fin Tuna",
    malayalamName: "കേര ചൂര",
    preparation: "Cleaned",
    packaging: "Thermal Box",
    sizeSpec: "5-10 kg/pc",
    priceDiamond: 7.92,
    pricePlatinum: 8.27,
    priceGold: 8.61,
    priceSilver: 8.96
  },
  {
    id: "25/CC/VA/1",
    code: "25/CC/VA/1",
    englishName: "Yellow fin Tuna",
    malayalamName: "കേര ചൂര",
    preparation: "Curry cut",
    packaging: "Vacuum Pack",
    sizeSpec: "5-10 kg/pc",
    priceDiamond: 11.13,
    pricePlatinum: 11.62,
    priceGold: 12.10,
    priceSilver: 12.58
  }
];
